### ISSUE TITLE
[feature request] Be able to set an application logo for the app branding sake

### ISSUE THREAD

**Issue by Johnstands** [KaesDingeling/Hybrid-Menu#10]
If possible please add an option to set an application logo or title with Icon and can also redirect to the default/specific view.

i.e.:

```setTitle(icon, description)```
```setTitle(icon, description,view)```

![image](https://user-images.githubusercontent.com/15935932/28012988-267727fc-659a-11e7-8412-b3966ec2eaa4.png)

**Comment by KaesDingeling** [comment]
Do you mean this title?

http://i.imgur.com/raPbVM9.png

If so, you can get the label with one line:
`HybridMenu hybridMenu = new HybridMenu();`
`hybridMenu.getTopMenuLabel()`

**Comment by Johnstands** [comment]
ahhm, not really but I think adding a CSS rule will do the magic.. thank you..  ^_^ 

![image](https://user-images.githubusercontent.com/15935932/28014230-76fcbbe8-659e-11e7-8145-6d87d044fabd.png)
