### ISSUE TITLE
Error with scss

### ISSUE THREAD

**Issue by fabioebner** [KaesDingeling/Hybrid-Menu#13]
I add a dependency on pom.xml,

and after add the lines in myTheme.scss he dont find the @import "../../addons/hybrid-menu/hybrid-menu.scss";

I need to create? or u create automatic?

**Comment by KaesDingeling** [comment]
After completing the dependency you have to compile the widgetset, then you can compile the theme. Have it just sung and it works as it should.

**Comment by fabioebner** [comment]
don't works for me.. I run mvn clean install and when I start my app show just like this
![screen shot 2017-07-11 at 19 53 12](https://user-images.githubusercontent.com/2648675/28094383-a0fb2c98-6672-11e7-967e-65a6e3eb9d61.png)

**Comment by appreciated** [comment]
@fabioebner Would you mind us having a look into your POM, your UI Class and your Theme file?

**Comment by fabioebner** [comment]
Sure, this is my pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>br.com.exmart</groupId>
	<artifactId>indicadorRTDPJ</artifactId>
	<packaging>war</packaging>
	<version>1.0-SNAPSHOT</version>
	<name>indicadorRTDPJ</name>

	<prerequisites>
		<maven>3</maven>
	</prerequisites>

	<properties>
		<vaadin.version>8.0.5</vaadin.version>
		<vaadin.plugin.version>8.0.5</vaadin.plugin.version>
		<jetty.plugin.version>9.3.9.v20160517</jetty.plugin.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		
		<vaadin.widgetset.mode>local</vaadin.widgetset.mode>
	</properties>

	<repositories>
		<repository>
			<id>vaadin-addons</id>
			<url>http://maven.vaadin.com/vaadin-addons</url>
		</repository>
	</repositories>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-io</artifactId>
			<version>${jetty.plugin.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>5.4.1.Final</version>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>1.1.0.Final</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.0.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-server</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-push</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client-compiled</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-themes</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>22.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.8.8</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-jackson-provider</artifactId>
			<version>3.1.2.Final</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-client</artifactId>
			<version>3.1.2.Final</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.vaadin.addons</groupId>
			<artifactId>hybridmenu</artifactId>
			<version>0.0.1.17-ALPHA</version>
		</dependency>
		<dependency>
		   <groupId>com.github.appreciated</groupId>
		   <artifactId>material</artifactId>
		   <version>0.8.6</version>
		</dependency>
		<dependency>
		   <groupId>pl.pdfviewer</groupId>
		   <artifactId>pdfviewer</artifactId>
		   <version>1.3.5</version>
		</dependency>
		<dependency>
			<groupId>de.steinwedel.vaadin.addon</groupId>
			<artifactId>messagebox</artifactId>
			<version>4.0.21</version>
		</dependency>
	</dependencies>
	
		

	<build>
		<finalName>rtdpj</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					
					<packagingExcludes>WEB-INF/classes/VAADIN/widgetsets/WEB-INF/**</packagingExcludes>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack-one</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<includeGroupIds>com.github.appreciated</includeGroupIds>
							<includeArtifactIds>material</includeArtifactIds>
							<type>zip</type>
							<excludes>*</excludes>
							<includes>VAADIN/themes/**</includes>
							<outputDirectory>src/main/webapp/</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>update-theme</goal>
							<goal>update-widgetset</goal>
							<goal>compile</goal>
							
							<goal>compile-theme</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.0.0</version>
				
				<configuration>
					<filesets>
						<fileset>
							<directory>src/main/webapp/VAADIN/themes</directory>
							<includes>
								<include>**/styles.css</include>
								<include>**/styles.scss.cache</include>
							</includes>
						</fileset>
					</filesets>
				</configuration>
			</plugin>

			
			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>${jetty.plugin.version}</version>
				<configuration>
					<scanIntervalSeconds>2</scanIntervalSeconds>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			
			<id>vaadin-prerelease</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>

			<repositories>
				<repository>
					<id>vaadin-prereleases</id>
					<url>http://maven.vaadin.com/vaadin-prereleases</url>
				</repository>
				<repository>
					<id>vaadin-snapshots</id>
					<url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<id>vaadin-prereleases</id>
					<url>http://maven.vaadin.com/vaadin-prereleases</url>
				</pluginRepository>
				<pluginRepository>
					<id>vaadin-snapshots</id>
					<url>https://oss.sonatype.org/content/repositories/vaadin-snapshots/</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</pluginRepository>
			</pluginRepositories>
		</profile>
	</profiles>

</project>


and this is my theme

@import "../../addons/hybrid-menu/hybrid-menu.scss";

@mixin mytheme {
  @include hybrid-menu;
  @include valo;
  @include material;
  ..
}

to work, i need to create the file hybrid-menu.scss in my VAADIN folder, and copy and past the scss from r github 💃

**Comment by appreciated** [comment]
First run a `mvn clean install`

If you take now a look in your `webapp/VAADIN/mytheme/addon.scss` file it should look something like this:
````
@import "../../../VAADIN/addons/hybrid-menu/hybrid-menu.scss";

@mixin addons {
	@include hybrid-menu;
}
````

Second try to remove the include and the import of the hybrid-menu.scss completely (since the material theme bases on valo you actually won't need the `@include valo` either)

Your  `webapp/VAADIN/mytheme/mytheme.scss`  should now look like this:
````
@import "../material/material.scss";

@mixin mytheme {
    @include material;
    ...
}
```` 
Also don't forget to compile the theme and to clear your browser cache, when restarting the application.

**Comment by fabioebner** [comment]
Nice I wiil try, one more doubt, how can I use a navigator?? I use this code:

HybridMenu hybridMenu = new HybridMenu();
        hybridMenu.createItemTitle(EMenuPosition.LEFT, "General", true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Home", FontAwesome.HOME, DashboardImpl.class, true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Settings", FontAwesome.COG, DashboardImpl.class, true);

but don`t change to my view.

tks

**Comment by KaesDingeling** [comment]
The navigator is set automatically and can be called via UI.getCurrent().GetNavigator()

**Comment by fabioebner** [comment]
So if the navigator are set automatically, why when I click in one button the view don`t change to my DashboardImpl.class?

**Comment by KaesDingeling** [comment]
Can you give me the contents of your Main class?

@Override
protected void init(VaadinRequest request) {
 /* this */
}

**Comment by fabioebner** [comment]
Sure I only copy and past r sample and change the classes to my own:

@Override
    protected void init(VaadinRequest vaadinRequest) {


        HybridMenu hybridMenu = new HybridMenu();
        hybridMenu.createItemTitle(EMenuPosition.LEFT, "General", true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Home", FontAwesome.HOME, DashboardImpl.class, true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Settings", FontAwesome.COG, DashboardImpl.class, true);
        MenuItem subMenu = hybridMenu.createItem(EMenuPosition.LEFT, "Settings", FontAwesome.COG, null, false);
        MenuItem settingsPage = hybridMenu.createItem(EMenuPosition.LEFT, "Settings", FontAwesome.COG, DashboardImpl.class, false);
        MenuItem groupPage = hybridMenu.createItem(EMenuPosition.LEFT, "Groups", FontAwesome.USERS, DashboardImpl.class, false);
        MenuItem memberPage = hybridMenu.createItem(EMenuPosition.LEFT, "Member", FontAwesome.USER, DashboardImpl.class, false);

        subMenu.addSubMenuItem(settingsPage);
        subMenu.addSubMenuItem(groupPage);
        subMenu.addSubMenuItem(memberPage);

        hybridMenu.addItem(subMenu);

        hybridMenu.createItemIconTitle(EMenuPosition.LEFT, FontAwesome.DASHBOARD.getHtml() + "General", true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Home", FontAwesome.HOME, DashboardImpl.class, true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Settings", FontAwesome.COG, DashboardImpl.class, true);
        hybridMenu.createItem(EMenuPosition.LEFT, "Default", FontAwesome.COG, DashboardImpl.class, true);

        MenuItem topHomePage = hybridMenu.createItem(EMenuPosition.TOP, "Home", FontAwesome.HOME, DashboardImpl.class, true);

        topHomePage.getButton().addStyleName(ETopMenuPosition.RIGHT.toString());


        MenuItem userSettings = hybridMenu.createItem(EMenuPosition.TOP, new ThemeResource("images/profilDummy.jpg"), false);
        MenuItem logout = hybridMenu.createItem(null, FontAwesome.SIGN_OUT.getHtml() + "Logout", DashboardImpl.class, false);

        userSettings.getButton().addStyleName("buttonWithoutCaption");
        userSettings.getButton().addStyleName(ETopMenuPosition.RIGHT.toString());
        userSettings.addSubMenuItem(logout);

        hybridMenu.addItem(userSettings);
        setContent(hybridMenu);
//        navigator.navigateTo("teste");
    }

and my DashboardImpl.class have a few components

**Comment by KaesDingeling** [comment]
If you create a button `hybridMenu.createItem(..` and there for example the DashboardImpl.class, the system makes everything for you by itself. You do not need to write a navigateTo or add the view to the navigator.

If you and this is the case here come to the same view on which one is already, the navigation is ignored. You can do this by doing the 

`MenuItem menuItem = hybridMenu.createItem(EMenuPosition.LEFT, "Settings", FontAwesome.COG, DashboardImpl.class, true);`
`menuItem.setAllowNavigateToSamePage(true);`

Likewise, you do not need to make a `new Navigator(...` This happens all by itself.


I hope I could help you.
