### ISSUE TITLE
Make menus visible/invisible

### ISSUE THREAD

**Issue by marocms-com** [KaesDingeling/Hybrid-Menu#19]
Hi,
I would like to have full controll over the menus. In my project i don't need to show the topMenu, so it will be great if we can get the opportunity to make them visible or invisible.

**Comment by appreciated** [comment]
Hello!
Good news is that [this is actually already possible by setting the variant / type of the menu](https://github.com/KaesDingeling/Hybrid-Menu/blob/a90229235f6033ccbe791704319d4f4285ff4162/HybridMenu-demo/src/main/java/kaesdingeling/hybridmenu/demo/DemoUI.java#L35). Bad news are, not in the version currently available in the Addon Directory. Also [the builder api could use some polishing, to allow setting a custom MenuVariant directly](https://github.com/KaesDingeling/Hybrid-Menu/blob/a90229235f6033ccbe791704319d4f4285ff4162/HybridMenu-addon/src/main/java/kaesdingeling/hybridmenu/menu/HybridMenu.java#L35). 
I try to get in touch with the maintainer, to update the version in the directory soon.

**Comment by appreciated** [comment]
I just added a pull request concerning a the api improvements.

**Comment by marocms-com** [comment]
ok, that sounds great.
