### ISSUE TITLE
NotificationCenter Open/Close

### ISSUE THREAD

**Issue by fo0** [KaesDingeling/Hybrid-Menu#24]
I need to open/close the notificationcenter programmatically

Could be nice if you implement something like:

```
NotificationCenter.setState(ENotificationState.Open);
NotificationCenter.setState(ENotificationState.Closed);
```

**Comment by KaesDingeling** [comment]
In version 2.0.3 you can use these 2 to call the Notification Center to control whether it should be opened without user interaction.

```
notificationCenter.setOpen(boolean open);
notificationCenter.isOpen(); // retuns boolean
```
