### ISSUE TITLE
NotificationCenter items in reverse order

### ISSUE THREAD

**Issue by fo0** [KaesDingeling/Hybrid-Menu#25]
The items are displayed in wrong order.
For example:

I add 3 items, every year one. It should be displayed the latest items first.
Im adding:
first item: 2017
second item: 2018
third item: 2019

You display: 
2017
2018
2019

You SHOULD display:
2019
2018
2017

**Comment by KaesDingeling** [comment]
The enum for this funktion is EMenuNotificationCenterSort and can be edit in the MenuConfig on the Version 2.0.3
