### ISSUE TITLE
complaining about missing jar files during server startup

### ISSUE THREAD

**Issue by sudhishvnair** [KaesDingeling/Hybrid-Menu#32]
Hi,

    I am using SPRING boot version v1.5.6.RELEASE. I am getting some jar file missing issues while starting up the application. I am able to do mvn:clean install
[errorSpringBoot.txt](https://github.com/KaesDingeling/Hybrid-Menu/files/1358486/errorSpringBoot.txt)

**Comment by KaesDingeling** [comment]
Hi,

does your project work with version 2.0.3?

**Comment by sudhishvnair** [comment]
Hi,

   Sorry for replying late. It is not working with 2.0.3 version as well. If I add the JAR as an external dependency from eclipse I can run the project

**Comment by KaesDingeling** [comment]
Actually I don't support Spring. Maybe in later versions, but currently not. Sorry. But if you want, you are welcome to do a pull request and fix the problem.
