### ISSUE TITLE
Scroll bar for the leftMenu

### ISSUE THREAD

**Issue by Johnstands** [KaesDingeling/Hybrid-Menu#35]
There is no scroll bar in the left menu, when the menu item overflows.

![image](https://user-images.githubusercontent.com/15935932/31750295-b30cee48-b4b1-11e7-8da3-b53981151d48.png)

**Comment by Johnstands** [comment]
I implemented a fix for this. #36

**Comment by KaesDingeling** [comment]
Thank you, the change can be found in version 2.0.7
