### ISSUE TITLE
integrate Hybrid-Menu with Spring

### ISSUE THREAD

**Issue by saadshareef** [KaesDingeling/Hybrid-Menu#39]
Hi,

Did you try using the HybridMenu with Spring Boot? any example???

Thanks
-Saad

**Comment by KaesDingeling** [comment]
I tested my addon with Spring Boot on a standard example of Vaadin "Bakery App".

Besides, I didn't have to make any adjustments. I put the code of my demoUI in there and it works without errors.

Link to the "Bakery App": https://vaadin.com/start

**Comment by saadshareef** [comment]
Thanks for response.
I added some of the code from demoUI to the Spring boot; when click on the HOME button showView is not executed.
On the other hand, typing the URL executes showView and displays the view in the proper displayView.

Could you please take a look at the sample on https://github.com/saadshareef/hmDemo01

Thanks
-Saad

**Comment by KaesDingeling** [comment]
In your example, I have changed the corresponding line.
The changes can be found in the pull request

That the view will be added automatically I will add in the next version.

**Comment by saadshareef** [comment]
Thanks for help out.
