### ISSUE TITLE
Dependency Injection (DI) not working

### ISSUE THREAD

**Issue by saadshareef** [KaesDingeling/Hybrid-Menu#41]
Hi,

Looks like DI not working.
Also, @postConstruct has not working as well.

Could you please take a look;
https://github.com/saadshareef/hmDemo01

```
public class HomePage extends VerticalLayout implements View {
	@Autowired
	ViewGreeter viewGreeter;

	@PostConstruct
    void init() {
		addComponent(new Label("HOME PAGE postConstruct"));
    }
}
```

Thanks
-Saad

**Comment by KaesDingeling** [comment]
I hardly work with Spring Boot, but you can use the constructor of the class that works.

```
public class HomePage extends VerticalLayout implements View {
	@Autowired
	ViewGreeter viewGreeter;

	public HomePage() {
		addComponent(new Label("HOME PAGE postConstruct"));
	}
}
```
Alternatively, you can watch the demo of Vaadin and see how they did it. For this you have to adjust the navigator.

The demo can be found here: https://bakery.demo.vaadin.com/login.html
You can download it here: https://vaadin.com/start
