### ISSUE TITLE
Content enable/disable

### ISSUE THREAD

**Issue by zaheer1389** [KaesDingeling/Hybrid-Menu#42]
need support to make content enable/disable as some users may want only left menu or right menu

**Comment by KaesDingeling** [comment]
``` Java
hybridmenu.setLeftMenuVisible(boolean visible);
hybridmenu.setTopMenuVisible(boolean visible);
hybridmenu.getContent().setVisible(boolean visible);
```

With the 3 lines you can change the visibility of the left and top menu. The content can also be changed in visibility.

In version 3.0.0 and higher the visibility can be changed this way:

``` Java
hybridmenu.getLeftMenu().setVisible(boolean visible);
hybridmenu.getTopMenu().setVisible(boolean visible);
hybridmenu.getContent().setVisible(boolean visible);
```
