### ISSUE TITLE
notification title missing length check

### ISSUE THREAD

**Issue by fo0** [KaesDingeling/Hybrid-Menu#48]
please check the length of the notification title. Sometimes its too long and then it wraps out of the notification-window-box

use: ```StringUtils.abbreviate(str, maxWidth)``` of Apache Commons lang

**Comment by KaesDingeling** [comment]
The bug was fixed in version 3.0.8

**Comment by KaesDingeling** [comment]
menu.getConfig().setNotificationPopupMaxContentLength(int - default 100);
menu.getConfig().setNotificationButtonLinePosition(NotificationPosition - default Bottom);
