### ISSUE TITLE
[Vaadin 10] Using TopMenu and LeftMenu seperately

### ISSUE THREAD

**Issue by LT-AMC** [KaesDingeling/Hybrid-Menu#52]
How would I go about using the TopMenu and LeftMenu seperately from the HybridMenu? We are using a border layout as frame for our application and would like to put the TopMenu and LeftMenu into different Layouts, without using the whole HybridMenu. I tried getting the components from the HybridMenu and adding them to the layouts, but it seems that the CSS styles do not apply then. Would it work if I just edited the CSS, or would using the menus seperately cause unsuspected issues?

**Comment by KaesDingeling** [comment]
It is generally possible to use the left and top menu items separately. I will make the necessary css changes in the coming days.

**Comment by KaesDingeling** [comment]
I unmounted the CSS so you can use the components separately

**Comment by LT-AMC** [comment]
It still seems to be not working. If I do something like this:
```
HybridMenu hm = new HybridMenu() {...};
VerticalLayout vert = new VerticalLayout();
HorizontalLayout hor = new HorizontalLayout();

vert.add(hm.getLeftMenu());
hor.add(hm.getTopMenu());

add(vert, hor);
```
the problem persists. The CSS-Styles are not being loaded correctly if I never add the HybridMenu itself to the site.

**Comment by KaesDingeling** [comment]
That's right, I missed it. You can add the style here. Where doesn't matter.

```
import de.kaesdingeling.hybridmenu.components.Style;
import de.kaesdingeling.hybridmenu.design.DesignItem;
import de.kaesdingeling.hybridmenu.utils.Styles;

public void setHybridMenuStyles(DesignItem designItem) {
	Style style = new Style().setStyle(Styles.style);
	Style customStyle = new Style().setStyle(designItem.convertToStyle());
	
	add(style, customStyle);
}
```
