### ISSUE TITLE
Support for Vaadin10 rc5

### ISSUE THREAD

**Issue by LT-AMC** [KaesDingeling/Hybrid-Menu#54]
Do you plan on upgrading the HybridMenu to Vaadin10 1.0, since the RC is already available?

**Comment by KaesDingeling** [comment]
Yes, I just upgraded the project to the latest version. The version number is 3.0.9.vaadin10 and is built with version rc5. https://gitlab.com/KaesDingeling/Hybrid-Menu/issues/55
