### ISSUE TITLE
Vaadin 10 release version rename VaadinIcons to VaadinIcon

### ISSUE THREAD

**Issue by leotu** [KaesDingeling/Hybrid-Menu#55]
com.vaadin.flow.component.icon.VaadinIcons 
should rename to 
com.vaadin.flow.component.icon.VaadinIcon

Ref:
https://github.com/vaadin/vaadin-icons-flow/issues/23

**Comment by KaesDingeling** [comment]
The problem has already been solved. https://gitlab.com/KaesDingeling/Hybrid-Menu/issues/53

Please update the HybridMenu version to 3.0.11.vaadin10 or newer
