### ISSUE TITLE
[feature request] speed of submenu opening

### ISSUE THREAD

**Issue by fo0** [KaesDingeling/Hybrid-Menu#7]
Please add an option to modify the speed for submenu opening animation.

i.e.:
`
enum SubMenuSpeed{
 Low, Middle, High
}
`

**Comment by KaesDingeling** [comment]
It is possible to change the speed of the animations

`setMenuResizeSpeed(menuResizeSpeed); -> Default: High`
`setSubMenuSpeed(subMenuSpeed); -> Default: High`
