### ISSUE TITLE
[feature request] Set the Mode whether the menu is minimize or maximize only

### ISSUE THREAD

**Issue by Johnstands** [KaesDingeling/Hybrid-Menu#8]
Please add an option to set the primary mode of the menu and set if can be toggle or not.

i.e.:
```enum MenuMode{ Minimize_Only, Maximize_Only, Toggleable } ```
or
```setToggle(false);```
or
```setToggleVisible(false);```

**Comment by KaesDingeling** [comment]
Thanks for the good idea. I am implementing this function today.
