### ISSUE TITLE
[feature request] add more layouts for the content

### ISSUE THREAD

**Issue by fo0** [KaesDingeling/Hybrid-Menu#9]
I am not that familiar with CssLayouts. Anyway its a pretty nice menu. Could you provide me optionally an basic VerticalLayout ?

**Comment by KaesDingeling** [comment]
In version 0.0.1.14-ALPHA (1#14 ALPHA), you can submit a layout that is automatically added. Here all possibilities one to hand over:

`new HybridMenu(<Layout> content);`
`new HybridMenu(<boolean> customNavigator, <Layout> content);`

In the next version, these layouts are also supported with CSS to avoid display errors.
